### PR TITLE
parse ref field into separate columns for styling

### PR DESCRIPTION
**Pull request by PetersonGIS**
See https://github.com/go-spatial/tegola-web-demo/issues/21

### CODE REVIEW

**Comment by PetersonGIS** [comment]
If this PR is accepted, the tile cache will need to be re-created. Then I'll work on submitting the style changes to camo and mobility that will use the new ref fields. Existing styles won't break because the original ref field is still there.

**Comment by ARolek** [comment]
@PetersonGIS apologies for the delay on this review. Your strategy looks generally fine. A couple questions: 

- Have you tried this strategy when there are less than 4 refs? If so, does PostGIS handle it fine?
- Will we ever have more than 4 refs and need a more robust strategy?

**Comment by PetersonGIS** [comment]
Great questions. 

- I have tested this with refs of differing numbers. The reason it works is because the style has a layer for each case, which is the only way to get it to show multiple highway numbers on a line. So there's a style for the first ref. Then there's the style for the 2nd ref (if not null), then the style for the 3rd ref if not null, and so on. Essentially it is all taken care of the style.json and it does work.

- This seemed important to find out, so querying overpass turbo* yields: there are plenty of instances of 7 refs. There is one legit instance of 8 refs in Indiana on that highway that goes in a circle around Indianapolis. 8+ aren't looking legit: mostly train platforms where we wouldn't want to do this kind of style anyway. So to be safe we might want to change the PR so it includes up to 7 refs.

*way["highway"] ["ref"~ ".+;.+;.+;.+;.+;.+"]({{bbox}});

**Comment by PetersonGIS** [comment]
The code is updated to include up to 8 refs. Tested locally:

i465

**Comment by ARolek** [comment]
LGTM.

**Pull request merged**
