### PR TITLE
Rewrite setup instuctions in Readme for clarity 

### PR DESCRIPTION
**Pull request by adamakhtar**
This PR makes the setup instructions a little more explicit to help avoid any confusion (especially for OSM / Tegola beginners ). 

Impetus for this PR comes from the discussion on this issue https://github.com/go-spatial/tegola-osm/issues/59#issuecomment-650293089

This originally started out as a personal blog post but I decided to just rewrite it and submit it as a PR. If its a little too verbose I have no problem with it being rejected or modified to suit the project's needs.

### CODE REVIEW

**Comment by ARolek** [comment]
@adamakhtar thanks for keeping this PR going, and apologies for the slow action on my end. I'm starting to make some updates to the documentation for tegola and I will get this in the queue. Your efforts are very much appreciated!

**Comment by adamakhtar** [comment]
@ARolek ahh I just realised my last commit shouldn't have been on this branch. Let me remove that and repush. I'll do that today or in the next few days.

**Comment by adamakhtar** [comment]
@ARolek related to my last comment, can I remove the last commit and **force push** the branch back up? Doesn't make sense for it to be part of this projects commit history.

**Comment by ARolek** [comment]
@adamakhtar a force push should be fine.

**Comment by adamakhtar** [comment]
@ARolek I have force pushed and the unwanted commit is no longer present. Sorry for the bother.

**Comment by ARolek** [comment]
Thank you for the contribution! Sorry I was so slow to go through this, but your enhancements are very much appreciated.

**Comment by adamakhtar** [comment]
Awesome, thanks @ARolek !

**Pull request merged**
